# Generated by Django 4.2.11 on 2024-04-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicionesAire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='UnidadMedicion',
        ),
    ]
