# Generated by Django 4.2.11 on 2024-04-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicionesAire', '0002_rename_task_unidadmedicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadmedicion',
            old_name='description',
            new_name='significado',
        ),
        migrations.RenameField(
            model_name='unidadmedicion',
            old_name='title',
            new_name='simbolo',
        ),
    ]
