# Generated by Django 4.2.11 on 2024-04-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicionesAire', '0003_rename_description_unidadmedicion_significado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmedicion',
            name='done',
        ),
    ]
